# Generated by Django 6.0 on 2025-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_length_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ManyToManyField(null=True, related_name='passengers', to='flights.flight'),
        ),
    ]
